[pytest]
addopts = --alluredir ../AllureReport
		  --clean-alluredir
markers =
        DEMO
        SANITY
        FOCUSED
        SMOKE
        SMOKE_CLIENT
        SANITY_CLIENT
        FOCUSED_CLIENT