def TC_Content(number):
    return testCases_Content[number - 1]


testCases_Content = [
    ['Check the add new content option'],
    ['Check Add new content name'],
    ['Check Add new content name with non-supported input'],
    ['Check screen orientation options availability'],
    ['Check the Resolution options for Horizontal screen orientation'],
    ['Check the Resolution options for vertical Screen orientation'],
    ['Check custom resolution set for content'],
    ['Check the templates to create new content'],
    ['Check able to create content using a blank template'],
    ['Check able to create content using Document template'],
    ['Check able to add the PPT file to document type content'],
    ['Check able to add the Docx file to document type content'],
    ['Check able to add the PDF file to document type content'],
    ['Check able to cancel the processing of slides creation'],
    ['Check If able to edit the content created using Document template'],
    ['Check if able to edit the slide of the content created using Document templates'],
    ['Check able to create content using Playing video template'],
    ['Check able to add the video as background '],
    ['Check if able to edit content with video background'],
    ['Check if edit the slide of content with video background'],
    ['Check able to create content using Splitting screen'],
    ['Check able to select the split screen template option from the screen.'],
    ['Check able to change the background of the split content'],
    ['Check able to set video or documents as a background of content slide'],
    ['Check if able to edit the content created using split template'],
    ['Check if able to open the edit slide screen of the content'],
    ['Check if able to add new slide to the content'],
    ['Check if able to copy slide to the content'],
    ['Check if able to delete the slide of the content'],
    ['Check if able to select the individual slide of the split screen templates'],
    ['Check able to drag and drop the material to the split screens'],
    ['Check if able to modify the split screen area on the edit slide screen.'],
    ['Check if able to add objects to the split screens'],
    ['Check if able to delete the object from the split screen of the slide'],
    ['Check if able to add the objects to each split screens of the slide.'],
    ['Check if able to identify the type of object added to the split screen'],
    ['Check if able to add multiple objects to the single split screen'],
    ['Check able to see the created content list on screen'],
    ['Check able to search the created content from the list'],
    ['Check if able to select multiple content '],
    ['Check redirecting to content page by click on the content name from the list'],
    ['Check redirecting to playlist of the content form home screen'],
    ['Check redirecting to Schedules of the content form home screen'],
    ['Check content preview from the list'],
    ['Check copy the existing content'],
    ['Check sorting options on content list'],
    ['Check more options menu '],
    ['Check able to move content to other folder'],
    ['Check move content to trash '],
    ['Check copy the content to shared folder'],
    ['Check if able to delete the content from shared folder'],
    ['Check add tag to content option'],
    ['Check add new tag option behavior'],
    ['Check select tag from existing list for the content'],
    ['Check if able to add more than one tag to content'],
    ['Check removal of tag from the content'],
    ['Check if able to select multiple tags while selecting or removing it from for the content'],
    ['Check add new folder option behavior'],
    ['Check able to create content in Root folder'],
    ['Check able to create content in Created folder'],
    ['Check if able to search the content form trashed folder'],
    ['Check the preview of the trashed content'],
    ['Check the restore trashed content'],
    ['Check delete the trashed content Completely '],
    ['Check edit content screen for new created content'],
    ['Check edit content screen for Existing content'],
    ['Check able to access the Shared Folder from the edit screen'],
    ['Check able to copy the materials to shared folder from edit content screen'],
    ['Check the Preview option of edit content page'],
    ['Check the save option behavior of edit content page'],
    ['Check close button behavior '],
    ['Check add slides option behavior'],
    ['Check delete slides from the edit content screen'],
    ['Check copy the slide from the edit content screen'],
    ['Check able to swap the slides on edit slides screen'],
    ['Check the content play time status on edit screen'],
    ['Check drag and drop audio to Content'],
    ['Check the audio checkbox option'],
    ['Check Edit Slide option behavior'],
    ['Check header options for Edit slide screen.'],
    ['Check Back option behavior from the Edit slide screen'],
    ['Check able to save the changes in slide'],
    ['Check able to view the preview of the slide'],
    ['Check close button behavior from the edit slide screen'],
    ['Check drag and drop material from Folder to Slide screen'],
    ['Check Edit slide menu options'],
    ['Check Add Object option behavior'],
    ['Check if able to add text object to slide'],
    ['Check if able to modify the Object box '],
    ['Check if able to delete the Object from the slide'],
    ['Check able to create the copy of the object '],
    ['Check if able to add Image object to slide'],
    ['Verify that user is able to delete video object'],
    ['Check if able to add Onscreen object to slide'],
    ['Check if able to add RSS feed object to slide'],
    ['Check if able to add YouTube object to slide'],
    ['Check if able to add Google object to slide'],
    ['Check if able to add Shape object to slide'],
    ['Check if able to add JioSaavn object to slide'],
    ['Check if able to add Instagram object to slide'],
    ['Check the duration option behavior for the slide'],
    ['Check to fit to screen option from edit screen.'],
    ['Check the transition effect option behavior'],
    ['Check able to set the transition effect'],
    ['Check Go back to home screen when no action performed checkbox option behavior'],
    ['Check able to add  the background image of  slide'],
    ['Check able to modify or delete background image from the slide'],
    ['Check the alignment option for the background image'],
    ['Check background color option behavior'],
    ['Check Background with image and background color'],
    ['Check Action option behavior'],
    ['Check Auto tap option behavior'],
    ['Check Transition effect in multiple object section'],
    ['Check set duration  in multiple object section'],
    ['Check Audio On functionality'],
    ['Check Fit to screen option'],
    ['Check Action option behavior'],
    ['Check slide by tap'],
    ['Check "Show navigation option"'],
    ['Check user able to deliver by use Multiple Slide in "Template for splitting screen"'],
    ['Check user able to use Multiple Slide in "Template for splitting screen"'],
    ['Check if able to deliver "multiple slide object" to display.'],
    ['Verify able to deliver the only one image slide using multislide.'],
    ['Verify able to deliver the only video slide using multislide.'],
    ['Verify able to deliver the multiple  image slides using multislide.'],
    ['Verify able to deliver the multiple  video slides using multislide.'],
    ['Verify that user able to take action "Text object to show "on text object through button object(Text).'],
    ['Verify that user able to take action "Image object to show" on image object through button object (image).'],
    ['Verify that user able to take action "Video object to show" on video object through button object (video).'],
    ['Verify that user able to take action "Onscreen text to show" on Onscreen object through button object (Show onscreen).'],
    ['Verify that user able to take action "Image slide to show" on multi slide object through button object (Show image slide).'],
    ['Verify that user able to take action "Rss Feed to show" on Rss Feed object through button object (Show Rss Feed).'],
    ['Verify that user able to take action "YouTube video to show" on YouTube object through button object (Show YouTube).'],
    ['Verify that user able to take action "Google data to show" on Google object through button object (Show google,image).'],
    ['Verify that user able to take action "Shape to show" on shape object through button object (Show shape).'],
    ['Verify that user able to take action "Show to Jiosaavn" on Jiosaavn object through button object (Jiosaavn, image).'],
    ['Verify that user able to take action "Show to Instagram data" on Instagram object through button object (Instagram, image).'],
    ['Verify that user able to take action "Show to cricket news" on cricket object through button object (cricket, image).'],
    ['Verify that user able to take action "Show to Facebook data" on Facebook object through button object (Facebook).'],
    ['Verify that user able to take action "Show to HDMI data" on HDMI object through button object (HDMI).'],
    ['Verify that user able to take action "Show to External webpage data" on External webpage object through button object (Show External webpage).'],
    ['Verify that user able to take action "Show to image" on  clock object through button object (image).'],
    ['Verify that user able to take action "Show to image" on weather widget object through button object (image).'],
    ['Verify "Area/object where action is set" functionality'],
    ['Verify "Action" option inside button object'],
    ['Verify that user able to see the action object in place of first object by clicking the button object name in preview as well as in external display'],
    ['Verify that user able to keep multiple button inside button box'],
    ['Verify that user able to take action "video object to show "on text object through button object over background image  .'],
    ['Verify multiple button object  that user able to take action " multiple Video to show" on multiple text object through multiple button object over background image with full screen'],
    ['Verify that user able to take action "image object to show "on text object through button object over background image with full screen mode  .'],
    ['Verify user is able to create HDMI object'],
    ['Verify Clickable video functionality'],
    ['Verify Image object in Split Screen Template'],
    ['Verify Video object in Split Screen Template'],
    ['Verify Text  object in Split Screen Template'],
    ['Verify On Screen Text object in Split Screen Template'],
    ['Verify RSS Feed object in Split Screen Template'],
    ['Verify YouTube object in Split Screen Template'],
    ['Verify Google object in Split Screen Template'],
    ['Verify Shape  object in Split Screen Template'],
    ['Verify JioSaavn  object in Split Screen Template'],
    ['Verify Instagram object in Split Screen Template'],
    ['Verify Cricket object in Split Screen Template'],
    ['Verify Facebook object in Split Screen Template'],
    ['Verify HDMI object in Split Screen Template'],
    ['Verify External Web object in Split Screen Template'],
    ['Verify WebCamera object in Split Screen Template'],
    ['Verify Clock object in Split Screen Template'],
    ['Verify Weather object in Split Screen Template'],
    ['Verify Button Box object in Split Screen Template'],
    ['Verify Button object in Split Screen Template'],
    ['Verify Weather Warning object in Split Screen Template'],
    ['Verify RSS Feed object in Split Screen Template'],
    ['Verify RSS Feed object in Split Screen Template'],
    ['Verify Multiple Slide object in Split Screen Template'],
    ['Verify input text field on Text Object'],
    ['Verify input text field on "On Screen Text "Object'],
    ['Verify user is able to create a ZIP object and able to deliver to display'],
    ['Verify user is able to create a HDMI object and able to deliver to display'],
    ['Verify HDMI object in Split Screen Template'],
    ['Verify ZIP file object in Split Screen Template'],
    ['Create a Text Object with name "Sample" , Left aligned , centred , BreeSerif Regular , Bold , with background image'],
    ['Create a Image object and insert 2 images in layer and add audio in background & button inside'],
    ['Create a video object and add a video which can have action button , which opens a new webpage on click'],
]