def TC_Displays(number):
    return testCases_Displays[number - 1]


testCases_Displays = [
    ['Verify add new display functionality'],
    ['Verify that user is able to add new display'],
    ['Verify that user is able to close add new Display On screen Display'],
    ['Verify show Password'],
    ['Verify whether user can select state and cities from dropdown'],
    ['Verify proper message is displayed if user enters a different password in password confirmation box'],
    ['Verify proper message is displayed if user enters less than 6 characters'],
    ['Verify proper message is displayed if user enters numbers as district name'],
    ['Verify that user is able to add new tag to an existing display'],
    ['Verify able to close add tag OSD'],
    ['Verify user is able to select existing tag from dropdown'],
    ['Verify that user is able to add multiple Tag'],
    ['Verify that user is able to remove Tag'],
    ['Verify that user is able to close remove Tag OSD'],
    ['Verify that user is able to delete a display'],
    ['Verify that user is able to close delete completely OSD'],
    ['Verify that user is able to export the list of displays created and their details as a CSV File'],
    ['Verify create New folder in Displays > Root page'],
    ['To verify enter all characters in name field of Create folder.'],
    ['To verify all special characters in Name filed of create folder'],
    ['To verify ADD functionality in create folder'],
    ['To verify cancel functionality in create folder.'],
    ['To verify X icon on create folder.'],
    ['Verify Head folder functionality'],
    ['Verify that user is able to select folders from Folder Dropdown'],
    ['Verify that user is able to search folder from folder drop down'],
    ['Verify Deliver Instantly Functionality'],
    ['Verify user is able to search display'],
    ['Verify user is able to select a display using checkbox'],
    ['Verify user is able to select Multiple Displays using Checkbox'],
    ['Verify user is able to search Folder'],
    ['Verify user is able to select a Folder using checkbox'],
    ['Verify user is able to select Multiple Folders using Checkbox'],
    ['Verify user is able to search Base'],
    ['Verify user is able to select a Base using checkbox'],
    ['Verify user is able to select Multiple Bases using Checkbox'],
    ['Verify user is able to search Tag'],
    ['Verify user is able to select a Tag using checkbox'],
    ['Verify user is able to select Multiple Tags using Checkbox'],
    ['Verify that user is able to deliver content by selecting a Display'],
    ['Verify that user is able to deliver content by selecting a Folder'],
    ['Verify that user is able to deliver content by selecting a Tag'],
    ['Verify Deliver Instantly Functionality by selecting a display from Display Table'],
    ['Verify that user is able to remove selected Items'],
    ['Verify that user is able to close Deliver OSD'],
    ['Verify that user is able to deliver the content now by selecting a display and assigning a schedule'],
    ['Verify that user is able to deliver the content at a later time by selecting a display and assigning a schedule'],
    ['Verify that user is able to deliver the content now by selecting a folder and assigning a schedule'],
    ['Verify that user is able to deliver the content at a later time by selecting a folder and assigning a schedule'],
    ['Verify that user is able to deliver the content now by selecting a base and assigning a schedule'],
    ['Verify that user is able to deliver the content at a later time by selecting a base and assigning a schedule'],
    ['Verify that user is able to deliver the content now by selecting a tag and assigning a schedule'],
    ['Verify that user is able to deliver the content at a later time by selecting a base and assigning a schedule'],
    ['Verify that user can deliver content at multiple displays at the Same Time'],
    ['Verify that user can add  a single new tag to multiple displays at the same time'],
    ['Verify that user can add  multiple  new tags to multiple displays at the same time'],
    ['Verify that user can add  a single existing tag to multiple displays at the same time'],
    ['Verify that user can add  multiple  existing tags to multiple displays at the same time'],
    ['Verify that user can remove the same tag from Multiple Displays'],
    ['Verify that user can delete multiple displays'],
    ['Verify that user can display details for a particular display'],
    ['Verify that user is able to close displays details OSD'],
    ['Verify that user is able to edit schedule by clicking on  Schedule'],
    ['Move Display Functionality'],
    ['Verify that user is able to close Move Display OSD'],
    ['Verify that user is able to edit display'],
    ['Verify that user is able to close edit Display OSD'],
    ['Verify user is able to edit display name and save it'],
    ['Verify user is able to change State name and save it'],
    ['Verify user is able to change city name and save it'],
    ['Verify user is able to change District name and save it'],
    ['Verify user is able to change Pincode and save it'],
    ['Verify user is able to change Store address and save it'],
    ['Verify user is able to change Sync role and save it'],
    ['Verify user is able to change Mobile number and save it'],
    ['Verify that user is able to Migrate Display'],
    ['Verify that user is able to delete Schedule'],
    ['Verify that user is able to change password of Display'],
    ['Verify that user can see Tag List'],
    ['Verify Bulk Create Functionality'],
    ['Verify Sort by Display ID'],
    ['Verify Sort by Display Name'],
    ['Verify Search Functionality'],
    ['Verify Search Icon Functionality'],
    ['Verify Show Entries based on entries selection'],
    ['Verify Show Entries'],
    ['Verify right arrow (>) on bottom right corner on Materials > Root page.'],
    ['Verify left arrow (<) on bottom right corner on Materials > Root page'],
    ['Move Display Functionality '],
    ['Verify that user is able to edit display'],
    ['Verify that user is able to Migrate Display'],
    ['Verify that user is able to delete Schedule'],
    ['Verify that user is able to change password of Display'],
]