def TC_Dashboard(number):
    return testCases_Dashboard[number - 1]


testCases_Dashboard = [
    ['TC1 - ' 'Check UI/UX of dashboard.'],
    ['TC2 - ' 'Verify able to see the JioSignage welcome page with JioSignage logo.'],
    ['TC3 - ' 'Verify default focus on dashboard bold text in JioSignage page.'],
    ['TC4 - ' 'Verify able to see the welcome page message on top left.'],
    ['TC5 - ' 'Check the behaviour when click on JioSignage logo'],
    ['TC6 - ' 'Verify user able to see the total display license details count.'],
    ['TC7 - ' 'Verify color coding of used and remaining in display license box.'],
    ['TC8 - ' 'Verify used/remain details in display license feature.'],
    ['TC9 - ' 'Verify Total display license details and used/remain details in display license feature are correct'],
    ['TC10 - ' 'Verify  user able to see the total storage details on storage box in dashboard page.'],
    ['TC11 - ' 'Verify storage details on storage box in dashboard page are correct.'],
    ['TC12 - ' 'Check user able to see the remaining storage details on storage box in dashboard page.'],
    ['TC13 - ' 'Check user able to unable to disable used and remains details on storage box in dashboard page.'],
    ['TC14 - ' 'Check user able to see the tool tip when we place the mouse pointer on storage circle.'],
    ['TC15 - ' 'Check user able to see the service plan page when we click on used storage and observe.'],
    ['TC16 - ' 'Verify server usage details on service plan page.'],
    ['TC17 - ' 'Check user able to see the used media uploaded details box in dashboard page.'],
    ['TC18 - ' 'Verify user able to see the total added count in media uploaded box.'],
    ['TC19 - ' 'Verify user able to see the images details after clicking images text inside media uploaded.'],
    ['TC20 - ' 'Verify user able to see the video details after clicking video text inside media uploaded.'],
    ['TC21 - ' 'Verify user able to see the documents details after clicking document text inside media uploaded.'],
    ['TC22 - ' 'Verify user able to see the audio details after clicking Audio text inside media uploaded.'],
    ['TC23 - ' 'Check Images Added are reflecting in Dashboard'],
    ['TC24 - ' 'Check Images deleted are reflecting in Dashboard'],
    ['TC25 - ' 'Check Videos Added are reflecting in Dashboard'],
    ['TC26 - ' 'Check Videos deleted are reflecting in Dashboard'],
    ['TC27 - ' 'Check Audios Added are reflecting in Dashboard'],
    ['TC28 - ' 'Check Audios deleted are reflecting in Dashboard'],
    ['TC29 - ' 'Check Documents Added are reflecting in Dashboard'],
    ['TC30 - ' 'Check Documents deleted are reflecting in Dashboard'],
    ['TC31 - ' 'Check user able to see the content details box in dashboard page.'],
    ['TC32 - ' 'Verify user able to see the total  count in content box.'],
    ['TC33 - ' 'Verify user able to see the approved status in content session.'],
    ['TC34 - ' 'Verify user able to see the pending task status in content box.'],
    ['TC35 - ' 'Verify user able to see the expires in week status from content section.'],
    ['TC36 - ' 'Verify user able to see the expired status from content section.'],
    ['TC37 - ' 'Click on expires in week section and observe the behaviour.'],
    ['TC38 - ' 'Click on expired section and observe the behaviour.'],
    ['TC39 - ' 'Check content Approved are correctly reflecting in Dashboard'],
    ['TC40 - ' 'Check content pending for Approval are correctly reflecting in dashboard'],
    ['TC41 - ' 'Check total count is reflecting correctly in Content Section'],
    ['TC42 - ' 'Check user able to see the playlist  details box in dashboard page.'],
    ['TC43 - ' 'Verify user able to see the total  count in playlist box.'],
    ['TC44 - ' 'Verify user able to see the approved status in playlist section.'],
    ['TC45 - ' 'Verify user able to see the pending task status in playlist box.'],
    ['TC46 - ' 'Check user able to see the Display status  details box in dashboard page.'],
    ['TC47 - ' 'Verify user able to see the total display  details count.'],
    ['TC48 - ' 'Verify color coding of used and remaining in display license box.'],
    ['TC49 - ' 'Verify online and offline details in display status section.'],
    ['TC50 - ' 'Check user able to see the Schedules details box in dashboard page.'],
    ['TC51 - ' 'Verify user able to see the total count in schedules section.'],
    ['TC52 - ' 'Check user able to see the State/city display details box in dashboard page.'],
    ['TC53 - ' 'Check user able to filter the state /city from drop down in  state/city box display in dashboard.'],
    ['TC54 - ' 'Verify filtered state/city details are reflecting on state/city display section.'],
    ['TC55 - ' 'Verify user able to select the filtered state/city details from state/city display section.'],
    ['TC56 - ' 'Check user able to see the tag wise display  box in dashboard page.'],
    ['TC57 - ' 'Check user able to see the tag wise display section count in dashboard page.'],
    ['TC58 - ' 'Verify user able to see the tagged display  count is reflecting on tag wise display in dashboard page.'],
    ['TC59 - ' 'Verify user able to see the bar chart in tag wise display section.'],
    ['TC60- ' 'Verify user able to see the tool tip when place mouse on bar chat.'],
    ['TC61 - ' 'Very user able to scroll the tag wise display section using scroll bar.'],
    ['TC62 - ' 'Verify user able to see the x and y axis in tag wise display section.'],
    ['TC63 - ' 'Check user able to see the display offline since details box in dashboard page.'],
    ['TC64 - ' 'Verify x-axis and y-axis  in display offline since details section.'],
    ['TC65 - ' 'Verify x-axis and y-axis representation in display offline since details.'],
    ['TC66 - ' 'Verify user able to see the display status from when on words display in offline.'],
    ['TC67 - ' 'Check user able to click bar chat on display in offline in dashboard page.'],
    ['TC68 - ' 'Check user able to see the state wise display details box in dashboard page.'],
    ['TC69 - ' 'Verify user able to scroll horizon direction in sate wise display section for more information.'],
    ['TC70 - ' 'Verify x-axis and y-axis representation in state wise display details.'],
    ['TC71 - ' 'Check user able to see the state wise online & offline graph on display in state wise display section.'],
    ['TC72 - ' 'Verify user able to enable and disable online and offline options in state wise display section.'],
    ['TC73 - ' 'Verify user able to see x-axis and y-axis representation text.'],
    ['TC74 - ' 'Verify user identify online and offline status.'],
    ['TC75 - ' 'Verify tool tip is showing when we place on graph.'],
    ['TC76 - ' 'Check user able to see the city wise display details box in dashboard page.'],
    ['TC77 - ' 'Verify user able to scroll horizon direction in city wise display section for more information.'],
    ['TC78 - ' 'Verify x-axis and y-axis representation in city wise display details.'],
    ['TC79 - ' 'Check user able to see the city wise online & offline graph on display in city wise display section.'],
    ['TC80 - ' 'Verify user able to enable and disable online and offline options in city wise display section.'],
    ['TC81 - ' 'Verify user able to see x-axis and y-axis representation text.'],
    ['TC82 - ' 'Verify user able to identify online and offline status.'],
    ['TC83 - ' 'Verify tool tip is showing when we place on graph.'],
    ['TC84 - ' 'Check user able to see the App version wise display details box in dashboard page.'],
    ['TC85 - ' 'Verify user able to see the app version wise display details .'],
    ['TC86 - ' 'Verify able to see the app version tool tip when we place the hover on bar chat.'],
    ['TC87 - ' 'Check user able to see the Platform wise display details box in dashboard page.'],
    ['TC88 - ' 'Verify user able to see the platform wise display details .'],
    ['TC89 - ' 'Verify user able to see the platform wise display count.'],
    ['TC90 - ' 'Check user able to see the platform details in platform wise display section.'],
    ['TC91 - ' 'Verify able to see the app version tool tip when we place the hover on bar chat.'],
    ['TC92 - ' 'Check user able to see the HDMI status details box in dashboard page.'],
    ['TC93 - ' 'Verify user able to see the HDMI display status details .'],
    ['TC94 - ' 'Verify able to see the HDMI connected status.'],
    ['TC95 - ' 'Verify able to see the HDMI dis connected status.'],
    ['TC96 - ' 'Verify user able to switch  head user account to base account.'],
    ['TC97 - ' 'Verify user able to switch  head user account to base account without selecting base account.'],
    ['TC98 - ' 'Verify ok and cancel button is working on select on base account page.'],
    ['TC99 - ' 'Check user able to select the view profile option.'],
    ['TC100 - ' 'Check user able to update the user name.'],
    ['TC101 - ' 'Check user able to click "save" and "cancel" option" from user name OSD.'],
    ['TC102 - ' 'Check user able to update the phone number.'],
    ['TC103 - ' 'Check user able to click "save" and "cancel" option" from new phone number OSD.'],
    ['TC104 - ' 'Verify user able to close the new phone number osd by clicking "X"'],
    ['TC105 - ' 'Check user able to update the password.'],
    ['TC106 - ' 'Check user able to update the password with two different password in two different field and observe.'],
    ['TC107 - ' 'Check user able to click "save" and "cancel" option" from new password OSD.'],
    ['TC108 - ' 'Verify user able to close the new phone number osd by clicking "X"'],
    ['TC109 - ' 'Verify user able to select the view service plan from profile.'],
    ['TC110 - ' 'Verify user able to select the help option from profile icon.'],
    ['TC111 - ' 'Verify user able to select the logout option from profile icon.'],
    ['TC112 - ' 'Click on FAQ and observe the behaviour.'],
    ['TC113 - ' 'Click on help and observe the behaviour.'],
    ['TC114 - ' 'Click on privacy policy and observe the behaviour.'],
    ['TC115 - ' 'Click on Terms and condition option and observe the behaviour.'],
    ['TC116 - ' 'Check user able to see the Location wise display details box in dashboard page.'],
    ['TC117 - ' 'Verify user able to zoom in and zoom out using + and - symbols which is available in left side top '
     'on location wise display section.'],
    ['TC118 - ' 'Verify user able to zoom in and zoom out using two finger pinch in /out on map.'],
    ['TC119 - ' 'Verify user able to see the city wise display locations on map.'],
    ['TC120 - ' 'Verify user able to see the created locations display is reflecting location wise display.'],
    ['TC121 - ' 'Verify user able to see the display status in location wise display page.'],
    ['TC122 -' 'Verify cable status showing correct cable status.'],
    ['TC123 - ' 'Verify Tag wise display details are correct'],
]

