def TC_Material(number):
    return testCases_Material[number - 1]


testCases_Material = [
    ['Verify Materials table should be empty when no Material are uploaded'],
    ['Verify add new Material functionality'],
    ['Verify drag and drop functionality in upload materials pop up'],
    ['Verify browse functionality'],
    ['Verify user is able to Upload JPEG File Type as a material'],
    ['Verify user is  able to Upload PNG  File Type as a material'],
    ['Verify user is able to upload GIF  File Type as a material'],
    ['Verify user is able to upload JFIF File  Type as a material'],
    ['Verify user is able to upload MP4  File Type as a material'],
    ['Verify user is able to upload MOV  File Type as a material'],
    ['Verify user is able to upload Webm  File Type as a material'],
    ['Verify user is able to upload MP3  File Type as a material'],
    ['Verify user is able to upload Ogg Vorbis  File Type as a material'],
    ['Verify user is able to upload WAV  File Type as a material'],
    ['Verify user is able to upload PDF File Type as a material'],
    ['Verify user is able to upload PPT File Type as a material'],
    ['Verify user is able to upload PPTX File Type as a material'],
    ['Verify user is able to upload DOCX File Type as a material'],
    ['Verify close button functionality in Upload Materials Page'],
    ['Verify supported file format details are available on upload Materials Page'],
    ['Verify that user is able to upload 9 multiple files at single time.'],
    ['Verify that user is able to upload 10 files'],
    ['Verify that user is able to upload 11 files'],
    ['Verify that user can remove the selected file in Upload Materials Page'],
    ['Verify that user can view the details of selected file in Upload Materials Page'],
    ['Verify that a Material that is selected to upload is valid'],
    ['Verify that user can remove all the selected materials in Upload Materials On screen Display'],
    ['Verify that user is able to upload Material (Image/video/audio/DOC/PPT/PDF )whose size is 1.99 GB'],
    ['Verify that user is able to upload file (Image/video/audio/DOC/PPT/PDF ) whose size is  2 GB'],
    ['Verify that user is able to upload file (Image/video/audio/DOC/PPT/PDF ) whose size is  2.1 GB'],
    ['Verify progress bar while uploading a material'],
    ['Verify Move to trash functionality'],
    ['Verify OK functionality in Move to trash pop-up'],
    ['Verify Cancel functionality in Move to trash pop-up'],
    ['Verify X functionality in move to trash pop up'],
    ['Verify Move Material Functionality'],
    ['Verify Move button functionality in Move Material OSD'],
    ['Verify close button functionality in Move Material OSD'],
    ['Verify Copy to shared functionality'],
    ['Verify Ok button in shared pop up'],
    ['Verify Cancel button in shared pop up'],
    ['Verify Close button in shared pop up'],
    ['Verify that user is able to create a  new playlist'],
    ['Verify that user is able to add Material to existing playlist'],
    ['Verify that user is able to search a Material by name'],
    ['Verify Search icon Functionality'],
    ['Verify Sort Functionality'],
    ['Verify create New folder in  Materials > Root page'],
    ['To verify enter all characters in name field of Create folder.'],
    ['To verify all special characters in Name filed of create folder'],
    ['To verify ADD functionality in create folder.'],
    ['To verify cancel functionality in create folder.'],
    ['To verify X icon on create folder.'],
    ['Verify Head folder functionality'],
    ['Verify Shared folder functionality'],
    ['Verify that user is able to view files present in Trash Folder'],
    ['Verify that user is able to filter Materials based on type'],
    ['Verify that user is able to select folders from Folder Dropdown'],
    ['Verify that user can preview the Materials'],
    ['Verify that user can rename the Material by clicking on Material Name'],
    ['Verify that user is able to close the preview page'],
    ['Verify that user can view the thumbnail'],
    ['Verify that user is able to Navigate to a particular folder'],
    ['Verify that user can edit a particular folder'],
    ['Verify that user can close edit folder pop up'],
    ['Verify user can move a folder to trash'],
    ['Verify that user is able to close the trash pop up'],
    ['Verify that user is able to search folder from folder drop down'],
    ['Verify that folder is accessible by clicking on the folder name in folder path'],
    ['Verify that tooltip is displayed by hovering on the selected option'],
    ['Verify that user can view the following details of the Materials 1. Thumbnail 2. Name 3. Folder 4. Details 5. Upload At  6. Materials Type'],
    ['Verify that user can select all the Materials that are available by clicking on All'],
    ['Verify that TAB and UDLR Keys are working on Materials page'],
    ['Verify that user is able to scroll up and down in Materials page'],
    ['Verify checkbox functionality in Materials > Root'],
    ['Verify checkbox functionality in Materials > Shared'],
    ['Verify checkbox functionality in Materials > Trashed'],
    ['Verify Show Entries based on entries selection'],
    ['Verify Show Entries'],
    ['Verify right arrow (>) on bottom right corner on Materials > Root page.'],
    ['Verify left arrow (<) on bottom right corner on Materials > Root page'],
]