def TC_Playlist(number):
    return testCases_playlist[number - 1]


testCases_playlist = [
    ['TC1 - ' 'To verify that create new playlist functionality in main playlist page.'],
    ['TC2 - ' 'To verify enter all characters in name field.'],
    ['TC3 - ' 'To verify all special characters in Name filed'],
    ['TC4 - ' 'To verify Add functionality in add new playlist OSD screen.'],
    ['TC5 - ' 'To verify cancel functionality in add new playlist OSD screen.'],
    ['TC6 - ' 'To verify X icon on add new playlist screen.'],
    ['TC7 - ' 'Verify created Playlist details in Playlist Page table'],
    ['TC8 - ' 'To verify edit playlist name functionality in edit playlist screen.'],
    ['TC9 - ' 'To verify update name functionality in edit playlist page.'],
    ['TC10 - ' 'To verify drag & drop functionality in edit playlist page.'],
    ['TC11 - ' 'To verify save functionality in edit playlist.'],
    ['TC12 - ' 'To verify No functionality in Confirmation of save the updated playlist in edit playlist screen.'],
    ['TC13 - ' 'To verify Yes functionality in Confirmation of save the updated playlist in edit playlist screen.'],
    ['TC14 - ' 'To verify X icon (close) functionality in edit playlist screen.'],
    ['TC15 - ' 'To verify No functionality in Confirmation of close the playlist in edit playlist screen.'],
    ['TC16 - ' 'To verify Yes functionality in Confirmation of close the playlist in edit playlist screen.'],
    ['TC17 - ' 'To verify duration in edit playlist screen.'],
    ['TC18 - ' 'To verify content folder in edit playlist screen.'],
    ['TC19 - ' 'To verify open and close the content folder in edit playlist screen.'],
    ['TC20 - ' 'To verify scroll up and down functionality in search content page on edit playlist screen.'],
    ['TC21 - ' 'To verify scroll up and down functionality in edit playlist screen.'],
    ['TC22 - ' 'To verify preview of individual content in playlist'],
    ['TC23 - ' 'TO verify individual delete content in Edit page of playlist'],
    ['TC24 - ' 'To verify Request for approval in Edit Playlist page'],
    ['TC25 - ' 'To verify Edit playlist page shows correct details of playlist'],
    ['TC26 - ' 'To verify close button in Edit Playlist'],
    ['TC27 - ' 'To verify Playlist Preview functionality available on Top right side of the Edit Playlist '
     'functionality page'],
    ['TC28 - ' 'To verify that Head Folder functionality in Playlist.'],
    ['TC29- ' 'To verify trashed functionality in playlist.'],
    ['TC30 - ' 'To verify search functionality in trashed playlist.'],
    ['TC31 - ' 'To verify check box functionality in  trashed playlist.'],
    ['TC32 - ' 'To verify more option in Trashed playlist'],
    ['TC33 - ' 'To verify Restore functionality in Trashed playlist'],
    ['TC34 - ' 'To verify "OK" functionality in Restore Confirmation pop up of Trashed playlist'],
    ['TC35 - ' 'To verify "Cancel" functionality in Restore Confirmation pop up of Trashed playlist'],
    ['TC36 - ' 'To verify "X" icon functionality in Restore Confirmation pop up of Trashed playlist'],
    ['TC37 - ' 'To verify Delete completely functionality in Trashed playlist'],
    ['TC38 - ' 'To verify "OK" functionality in delete Confirmation pop up of Trashed playlist'],
    ['TC39 - ' 'To verify "Cancel" functionality in Delete Confirmation pop up of Trashed playlist'],
    ['TC40 - ' 'To verify "X" icon functionality in delete Confirmation pop up of Trashed playlist'],
    ['TC41 - ' 'To verify sorting Functionality in trashed playlist.'],
    ['TC42 - ' 'To verify scroll up and down functionality in trashed playlist page.'],
    ['TC43 - ' 'To verify Number of entries in Trashed playlist page.'],
    ['TC44 - ' 'To verify right arrow (>) on bottom right corner on trashed playlist page.'],
    ['TC45 - ' 'To verify left arrow (<) on bottom right corner on trashed playlist page.'],
    ['TC46 - ' 'To verify preview icon functionality in trashed playlist.'],
    ['TC47 - ' 'To verify name of playlist in trashed playlist'],
    ['TC48 - ' 'To verify Folder of playlist in trashed playlist'],
    ['TC49 - ' 'To verify details of playlist in trashed playlist'],
    ['TC50 - ' 'To verify modified by in trashed playlist'],
    ['TC51 - ' 'To verify modified at in trashed playlist'],
    ['TC52 - ' 'To verify create folder functionality in Playlist main page.'],
    ['TC53 - ' 'To verify enter all characters in name field of Create folder.'],
    ['TC54 - ' 'To verify all special characters in Name filed of create folder'],
    ['TC55 - ' 'To verify ADD functionality in create folder.'],
    ['TC56 - ' 'To verify cancel functionality in create folder.'],
    ['TC57 - ' 'To verify X icon on create folder.'],
    ['TC58 - ' 'To verify dropdown icon of root in playlist main page.'],
    ['TC59 - ' 'To verify search functionality in folder dropdown of playlist main page'],
    ['TC60 - ' 'To verify select any folder over folder dropdown in playlist main page.'],
    ['TC61 - ' 'To verify search functionality in playlist main page.'],
    ['TC62 - ' 'To verify filter icon on schedule.'],
    ['TC63 - ' 'To verify check box functionality in playlist main screen.'],
    ['TC64 - ' 'To verify more option functionality in playlist.'],
    ['TC65 - ' 'To verify Move playlist functionality in playlist more option.'],
    ['TC66 - ' 'To verify dropdown functionality in move playlist OSD on playlist.'],
    ['TC67 - ' 'To verify X functionality in Move playlist OSD.'],
    ['TC68 - ' 'To verify Move functionality in Move playlist OSD.'],
    ['TC69 - ' 'To verify Move to trash functionality in Playlist.'],
    ['TC70 - ' 'To verify "OK" functionality in Confirmation OSD of playlist'],
    ['TC71 - ' 'To verify "Cancel" functionality in Confirmation OSD of playlist'],
    ['TC72 - ' 'To verify "X" icon functionality in Confirmation OSD of playlist'],
    ['TC73 - ' 'To verify Preview icon functionality in playlist main screen.'],
    ['TC74 - ' 'To verify Copy icon functionality in playlist main screen.'],
    ['TC75 - ' 'To verify enter all characters in name field of Copy playlist.'],
    ['TC76- ' 'To verify all special characters in Name filed of copy playlist'],
    ['TC77 - ' 'To verify Save functionality in copy playlist.'],
    ['TC78 - ' 'To verify cancel functionality in copy playlist.'],
    ['TC79 - ' 'To verify X icon on copy playlist.'],
    ['TC80 - ' 'To verify clicking on Playlist name in main playlist screen.'],
    ['TC81 - ' 'To verify Edit icon functionality in playlist.'],
    ['TC82 - ' 'To verify enter all characters in name field of edit playlist.'],
    ['TC83 - ' 'To verify all special characters in Name filed of edit playlist'],
    ['TC84 - ' 'To verify Save functionality in edit playlist.'],
    ['TC85 - ' 'To verify cancel functionality in edit playlist.'],
    ['TC86 - ' 'To verify X icon on copy playlist.'],
    ['TC87 - ' 'To verify Schedule count in playlist.'],
    ['TC88 - ' 'To verify details of playlist.'],
    ['TC89 - ' 'To verify modified by in playlist'],
    ['TC90 - ' 'To verify modified at in playlist'],
    ['TC91 - ' 'To verify scroll up and down functionality in playlist main page.'],
    ['TC92 - ' 'To verify Number of entries in playlist page.'],
    ['TC93 - ' 'To verify right arrow (>) on bottom right corner on playlist page.'],
    ['TC94 - ' 'To verify left arrow (<) on bottom right corner on playlist page.'],
    ['TC 95 -''Test name field for character , special char , number '],
    ['TC 96 -' 'Save playlist'],
    ['TC 97 -' 'To verify filter icon on playlist.'],
    ['TC 98 -' 'To verify filter icon on playlist.'],

]
