def TC_Schedules(number):
    return testCases_schedules[number - 1]


testCases_schedules = [
    ['TC1 - ' 'To verify that user is able to create new schedule'],
    ['TC2 - ' 'To verify enter all characters in name field.'],
    ['TC3 - ' 'To verify all special characters in Name filed'],
    ['TC4 - ' 'To verify ADD functionality in add new schedule screen.'],
    ['TC5 - ' 'To verify cancel functionality in add new schedule screen.'],
    ['TC6 - ' 'To verify X icon on add new schedule screen.'],
    ['TC7 - ' 'To verify Edit name functionality in Schedule page'],
    ['TC8 - ' 'To verify Update functionality in edit schedule name'],
    ['TC9 - ' 'To verify time duration functionality in schedule.'],
    ['TC10 - ' 'To verify cancel functionality in schedule screen.'],
    ['TC11 - ' 'To verify "Yes" functionality in Cancel Confirmation pop up'],
    ['TC12 - ' 'To verify "No" functionality in Cancel Confirmation pop up'],
    ['TC13 - ' 'To verify < icon on schedule screen.'],
    ['TC14 - ' 'To verify > icon on schedule screen.'],
    ['TC15 - ' 'To verify Today option on schedule screen.'],
    ['TC16 - ' 'To verify content search functionality in schedule screen.'],
    ['TC17 - ' 'To verify playlist search functionality in schedule screen.'],
    ['TC18 - ' 'To verify Drag and drop functionality in schedule screen'],
    ['TC19 - ' 'To verify Edit schedule details functionality in schedule screen'],
    ['TC20 - ' 'To verify preview option on edit schedule details page.'],
    ['TC21 - ' 'To verify start time functionality in edit schedule details page.'],
    ['TC22 - ' 'To verify end time functionality in edit schedule details page.'],
    ['TC23 - ' 'To verify the check box of "repeat the duration" in edit schedule details page.'],
    ['TC24 - ' 'To verify the start date option on edit schedule page when after enabled check box of repeat the '
     'duration.'],
    ['TC25 - ' 'To verify the End date option on edit schedule page when after enabled check box of repeat the '
     'duration.'],
    ['TC26 - ' 'To verify Save functionality in edit schedule details.'],
    ['TC27 - ' 'To verify cancel functionality in edit schedule details.'],
    ['TC28 - ' 'To verify delete functionality in edit schedule details.'],
    ['TC29 - ' 'To verify scroll up and down in Edit schedule screen.'],
    ['TC30 - ' 'To verify Folder functionality in Edit Schedule page'],
    ['TC31 - ' 'To verify scroll functionality in content pane in Edit Schedule page'],
    ['TC32 - ' 'To verify current date is displayed on Edit Schedule page'],
    ['TC33 - ' 'To verify Left and Right button on Edit Schedule page for changing Weeks'],
    ['TC34 - ' 'To verify close button functionality on Edit Schedule page'],
    ['TC35 - ' 'To verify "All Day" functionality in Edit Schedule page'],
    ['TC36 - ' 'To verify drag and drop playlist functionality'],
    ['TC37 - ' 'To verify Playlist Folder functionality in Edit Schedule page'],
    ['TC38 - ' 'To verify Add trigger functionality in schedule'],
    ['TC40 - ' 'Create a Trigger & Run'],
    ['TC41 - ' 'Verify Cancel button functionality in Add Trigger page'],
    ['TC42 - ' 'Verify Added trigger is showing in Trigger page '],
    ['TC43 - ' 'Verify  Edit name functionality in Add Trigger page'],
    ['TC44 - ' 'Verify Playlist and Content can be selected in Add Trigger page and able to run Trigger successfully'],
    ['TC45 - ' 'Verify Preferences option can be selected and able to successfully trigger it'],
    ['TC46 - ' 'Verify able To successfully add Schedule and able to trigger successfully'],
    ['TC47 - ' 'Verify able successfully add Repeat option and able to successfully trigger'],
    ['TC48 - ' 'To verify that Head Folder functionality in schedule root screen.'],
    ['TC49 - ' 'To verify that Trashed functionality in Schedule root screen'],
    ['TC50 - ' 'To verify search functionality in schedule > trashed.'],
    ['TC51 - ' 'To verify check box functionality in schedule > trashed.'],
    ['TC52 - ' 'To verify more option in schedule > trashed'],
    ['TC53 - ' 'To verify restore functionality in Schedule > trashed'],
    ['TC54 - ' 'To verify "OK" functionality in restore Confirmation pop up of schedule > trashed'],
    ['TC55 - ' 'To verify "Cancel" functionality in restore Confirmation pop up of schedule > trashed'],
    ['TC56 - ' 'To verify "X" icon functionality in restore Confirmation pop up of schedule > trashed'],
    ['TC57 - ' 'To verify Delete completely functionality in Schedule > trashed'],
    ['TC58 - ' 'To verify "OK" functionality in delete Confirmation pop up of schedule > trashed'],
    ['TC59 - ' 'To verify "Cancel" functionality in Delete Confirmation pop up of schedule > trashed'],
    ['TC60 - ' 'To verify "X" icon functionality in delete Confirmation pop up of schedule > trashed'],
    ['TC61 - ' 'To verify sorting Functionality in Schedule.'],
    ['TC62 - ' 'To verify scroll up and down functionality in trashed schedule page.'],
    ['TC63 - ' 'To verify Number of entries in Schedule page.'],
    ['TC64 - ' 'To verify right arrow (>) on bottom right corner on trashed schedule page.'],
    ['TC65 - ' 'To verify left arrow (<) on bottom right corner on trashed schedule page.'],
    ['TC66 - ' 'To verify create folder functionality in root schedule page.'],
    ['TC67 - ' 'To verify enter all characters in name field of Create folder.'],
    ['TC68 - ' 'To verify all special characters in Name filed of create folder'],
    ['TC69 - ' 'To verify ADD functionality in create folder.'],
    ['TC70 - ' 'To verify cancel functionality in create folder.'],
    ['TC71 - ' 'To verify X icon on create folder.'],
    ['TC72 - ' 'To verify dropdown icon of root in schedule'],
    ['TC73 - ' 'To verify search functionality in root dropdown'],
    ['TC74 - ' 'To verify select any folder over root dropdown.'],
    ['TC75 - ' 'To verify search functionality in schedule.'],
    ['TC76 - ' 'To verify filter icon on schedule.'],
    ['TC77 - ' 'To verify sorting Functionality in schedule.'],
    ['TC78 - ' 'To verify check box functionality in schedule.'],
    ['TC79 - ' 'To verify click on schedule name.'],
    ['TC80 - ' 'To verify drag and drop functionality after click schedule name in main schedule page.'],
    ['TC81 - ' 'To verify edit schedule details page while modifying the existing schedule.'],
    ['TC82 - ' 'To verify start time and end time in edit schedule details page when modifying the existing schedule.'],
    ['TC83 - ' 'To verify all functionality(preview, close ,save, delete and cancel) when modifying the existing '
     'schedule.'],
    ['TC84 - ' 'To verify time in dropped content in calendar sheet when modifying the existing schedule.'],
    ['TC85 - ' 'To verify Edit icon on schedule'],
    ['TC86 - ' 'To verify enter all characters in Edit schedule filed.'],
    ['TC87 - ' 'To verify all special characters in Name filed of Edit schedule filed.'],
    ['TC88 - ' 'To verify Save functionality in Edit schedule pop up screen.'],
    ['TC89 - ' 'To verify cancel functionality in create folder.'],
    ['TC90 - ' 'To verify X icon on Edit schedule pop up screen.'],
    ['TC91 - ' 'To verify edit icon on schedule.'],
    ['TC92 - ' 'To verify enter all characters in Edit schedule filed.'],
    ['TC93 - ' 'To verify all special characters in Name filed of Edit schedule filed.'],
    ['TC94 - ' 'To verify Save functionality in Edit schedule pop up screen.'],
    ['TC95 - ' 'To verify cancel functionality in create folder.'],
    ['TC96 - ' 'To verify X icon on Edit schedule pop up screen.'],
    ['TC97 - ' 'To verify Number of entries in Schedule page.'],
    ['TC98 - ' 'To verify right arrow (>) on bottom right corner on schedule page.'],
    ['TC99 - ' 'To verify left arrow (<) on bottom right corner on schedule page.'],
    ['TC100 - ' 'Verify copy function on Schedule page'],
    ['TC101 - ' 'To verify folder name in schedule'],
    ['TC102 - ' 'To verify Display count in Usage count.'],
    ['TC103 - ' 'To verify Delivery count in usage count'],
    ['TC104 - ' 'To verify start time and end time of schedule'],
    ['TC105 - ' 'To verify Total item of schedule'],
    ['TC106 - ' 'To verify modified by in schedule'],
    ['TC107 - ' 'To verify modified at in schedule'],
    ['TC108 - ' 'To verify scroll up and down functionality in schedule main page.'],
    ['TC109 - Verify able to successfully add Schedule and able to trigger successfully'],
    ['TC 110 - Verify able to successfully add Repeat option and able to successfully trigger'],
]
