def TC_UserAccess(number):
    return testCases_UserAccess[number - 1]


testCases_UserAccess = [
    ['Verify UI/UX of User Management page'],
    ['"Verify Hover functionality on User management Page"'],
    ['Verify User is able to add New Contractor user'],
    ['Verify User is able to add New Editor user'],
    ['Verify User is able to add New Advertiser user'],
    ['"Verify User is able to add New Custom Role account"'],
    ['Verify User cannot add New user with already used Mobile Number'],
    ['Verify User cannot add New user with already used Email'],
    ['Verify User can add New user with existing User Name'],
    ['Verify User is able to Cancel the add New user'],
    ['Verify User types on Add User Account page'],
    ['Verify Search Box Functionality'],
    ['Verify Search icon Functionality'],
    ['Verify Name Search Functionality'],
    ['Verify Email Address Search Functionality'],
    ['Verify Role Search Functionality'],
    ['Verify Permission Search Functionality'],
    ['Verify Activation Status Search Functionality'],
    ['Verify SORT By Name Functionality'],
    ['Verify SORT By Email Address Functionality'],
    ['Verify SORT By Role Functionality'],
    ['Verify SORT By Permission Functionality'],
    ['Verify SORT By Activation Status Functionality'],
    ['Verify Active User Deletion'],
    ['Verify Inactive/Pending User Deletion'],
    ['"Verify Add User Account page for Contractor User "'],
    ['"Verify Add User Account page for Editor User "'],
    ['"Verify Add User Account page for Advertiser User "'],
    [' Verify Add User Account page for Custom Role'],
    ['Verify Show Entries based on entries selection'],
    ['Verify Show Entries'],
    ['Add contractor with "Allow to delete completely folder/material/content/playlist/schedule" & Allow to delete base'],
    ['Add contractor with "Allow to delete completely folder/material/content/playlist/schedule"'],
    ['Add contractor with  Allow to delete base'],
    ['Add Editor with Allow to delete folder/material/content/playlist/schedule and Allow to add delivery/delivery instantly'],
    ['Add Editor with Allow to delete folder/material/content/playlist/schedule'],
    ['Add Editor with Allow to add delivery/delivery instantly'],
    ['Verify UI/UX of Base Management page'],
    ['Verify User able to Add New Base Account'],
    ['"Verify Hover functionality on Base management Page"'],
    ['"Verify User unable to Add New Base Account by clicking Cancel"'],
    ['Verify available options on Base Account'],
    ['Verify Edit Functionality on existing Base Account'],
    ['Verify Delete Functionality on existing Base Account'],
    ['Verify Trash of Base Management'],
    ['Verify UI/UX of Role Management page'],
    ['"Verify Hover functionality on Role management Page"'],
    ['Verify Add New Role functionality without Name'],
    ['Verify Add New Role functionality without any permission'],
    ['"Verify Added/Existing Role available for selection under User Management"'],
    ['Verify name is selectable & editable'],
    ['"Verify Permissions can be changed/modified against Role Name"'],
    ['Verify Search Box Functionality'],
    ['Verify Search icon Functionality'],
    ['Verify Name Search Functionality'],
    ['Verify Permission Search Functionality'],
    ['Verify User Search Functionality'],
    ['Verify SORT By Name Functionality'],
    ['Verify SORT By Permission Functionality'],
    ['Verify SORT By User Functionality'],
    ['Verify Role deletion functionality'],
    ['Verify Show Entries based on entries selection'],
    ['Verify Show Entries'],
    ['"Verify ""Users"" under Permissions while add/modify role under Role Management"'],
    ['Verify View User under Users on Assign Permissions page for add/modify Role'],
    ['Verify Create/Edit User under Users on Assign Permissions page for add/modify Role'],
    ['Verify Edit/Update User under Users on Assign Permissions page for add/modify Role'],
    ['Verify Delete User under Users on Assign Permissions page for add/modify Role'],
    ['Verify Enable/Disable User under Users on Assign Permissions page for add/modify Role'],
    ['"Verify ""Material"" under Permissions while add/modify role under Role Management"'],
    ['Verify View Materials under Material on Assign Permissions page for add/modify Role'],
    ['Verify Upload/Create/Edit Material under Material on Assign Permissions page for add/modify Role'],
    ['Verify Move Material/Copy to Shared under Material on Assign Permissions page for add/modify Role'],
    ['Verify Move to Trash under Material on Assign Permissions page for add/modify Role'],
    ['Verify Restore Material under Material on Assign Permissions page for add/modify Role'],
    ['Verify Delete Completely under Material on Assign Permissions page for add/modify Role'],
    ['"Verify ""Content"" under Permissions while add/modify role under Role Management"'],
    ['Verify View Content under Content on Assign Permissions page for add/modify Role'],
    ['Verify Create/Edit Content under Content on Assign Permissions page for add/modify Role'],
    ['Verify Move Content/Copy to Shared under Content on Assign Permissions page for add/modify Role'],
    ['Verify Move to Trash under Content on Assign Permissions page for add/modify Role'],
    ['Verify Restore Content under Content on Assign Permissions page for add/modify Role'],
    ['Verify Delete Completely under Content on Assign Permissions page for add/modify Role'],
    ['"Verify ""Playlist"" under Permissions while add/modify role under Role Management"'],
    ['Verify View Playlist under Playlist on Assign Permissions page for add/modify Role'],
    ['Verify Create/Edit Playlist under Playlist on Assign Permissions page for add/modify Role'],
    ['Verify Move Playlist under Playlist on Assign Permissions page for add/modify Role'],
    ['Verify Move to Trash under Playlist on Assign Permissions page for add/modify Role'],
    ['Verify Restore Playlist under Playlist on Assign Permissions page for add/modify Role'],
    ['Verify Delete Completely under Playlist on Assign Permissions page for add/modify Role'],
    ['"Verify ""Schedule"" under Permissions while add/modify role under Role Management"'],
    ['Verify View Schedule under Schedule on Assign Permissions page for add/modify Role'],
    ['Verify Create/Edit Schedule under Schedule on Assign Permissions page for add/modify Role'],
    ['Verify Move Schedule under Schedule on Assign Permissions page for add/modify Role'],
    ['Verify Move to Trash under Schedule on Assign Permissions page for add/modify Role'],
    ['Verify Restore Schedule under Schedule on Assign Permissions page for add/modify Role'],
    ['Verify Delete Completely under Schedule on Assign Permissions page for add/modify Role'],
    ['Verify "Display and Delivery" under Permissions while add/modify role under Role Management'],
    ['Verify View Display under Display and Delivery on Assign Permissions page for add/modify Role'],
    ['Verify Create/Edit Display under Display and Delivery on Assign Permissions page for add/modify Role'],
    ['Verify Move Display/Assign Schedule under Display and Delivery on Assign Permissions page for add/modify Role'],
    ['Verify Move to Trash under Display and Delivery on Assign Permissions page for add/modify Role'],
    ['Verify Restore Display under Display and Delivery on Assign Permissions page for add/modify Role'],
    ['Verify Delete Completely under Display and Delivery on Assign Permissions page for add/modify Role'],
    ['Verify Deliver under Display and Delivery on Assign Permissions page for add/modify Role'],
    ['Verify Sync under Display and Delivery on Assign Permissions page for add/modify Role'],
    ['Verify Reboot under Display and Delivery on Assign Permissions page for add/modify Role'],
    ['Verify "Play log" under Permissions while add/modify role under Role Management'],
    ['Verify Generate Played Log Reports under Playlog on Assign Permissions page for add/modify Role'],
    ['Verify "UserActivityLog" under Permissions while add/modify role under Role Management'],
    ['Verify Generate User Activity Log Reports under UserActivityLog on Assign Permissions page for add/modify Role'],
    ['Verify "Emergency Alert" under Permissions while add/modify role under Role Management'],
    ['Verify Emergency alert under Emergency Alert on Assign Permissions page for add/modify Role'],
]
